- src/main/java/com/sesac7/hellopet/domain/user/Service/UserService.java
- src/main/java/com/sesac7/hellopet/domain/user/controller/UserController.java
- src/main/java/com/sesac7/hellopet/domain/user/dto/request/UserRegisterRequest.java
- src/main/java/com/sesac7/hellopet/domain/user/dto/response/UserRegisterResponse.java
- src/main/java/com/sesac7/hellopet/domain/user/entity/User.java
- src/main/java/com/sesac7/hellopet/domain/user/entity/UserDetail.java
- src/main/java/com/sesac7/hellopet/domain/user/repository/UserDetailRepository.java
- src/main/java/com/sesac7/hellopet/domain/user/repository/UserRepository.java
- src/main/java/com/sesac7/hellopet/global/config/SecurityConfig.java
클라이언트가 회원가입 신청을 하고 서버(”/signup”)로 회원 정보 데이터를 보내면 서버가 데이터를 받아 DB에 저장하고 저장에 성공하면 성공했다는 response를 보냅니다.
> 유저가 회원가입을 합니다[#-back-7]

- src/main/java/com/sesac7/hellopet/common/utils/CustomUserDetails.java
- src/main/java/com/sesac7/hellopet/common/utils/JwtUtil.java
- src/main/java/com/sesac7/hellopet/domain/auth/authService/AuthService.java
- src/main/java/com/sesac7/hellopet/domain/user/Service/UserDetailsServiceImpl.java
- src/main/java/com/sesac7/hellopet/global/config/SecurityConfig.java
- src/main/java/com/sesac7/hellopet/global/filter/JwtFilter.java
유저가 엑세스 쿠키나 리프래시 쿠키를 가지고 있다면 쿠키를 파싱하여 유저를 확인하고 권한을 확인합니다.
> 유저의 권한을 확인합니다.[#-back-11]

- src/main/java/com/sesac7/hellopet/domain/user/Service/UserService.java
- src/main/java/com/sesac7/hellopet/domain/user/controller/UserController.java
- src/main/java/com/sesac7/hellopet/domain/user/dto/request/CheckField.java
- src/main/java/com/sesac7/hellopet/domain/user/dto/request/UserRegisterRequest.java
- src/main/java/com/sesac7/hellopet/domain/user/dto/response/ExistResponse.java
- src/main/java/com/sesac7/hellopet/domain/user/entity/UserDetail.java
- src/main/java/com/sesac7/hellopet/domain/user/repository/UserDetailRepository.java
- src/main/java/com/sesac7/hellopet/domain/user/repository/UserRepository.java
유저가 회원가입 할 시 버튼을 눌러 이메일, 닉네임, 전화번호를 중복확인 할 수 있습니다.
> 회원가입 시 이메일, 닉네임, 휴대전화 중복확인[#back-12]

- src/main/java/com/sesac7/hellopet/domain/user/Service/UserService.java
- src/main/java/com/sesac7/hellopet/domain/user/dto/request/UserRegisterRequest.java
중복확인 테스트 도중에 형식에 맞지 않는 데이터를 보내도 서비스까지 도달하는 현상이 발생하여 개선이 필요합니다.
> email, 닉네임, 전화번호에 @valid 추가

- src/main/java/com/sesac7/hellopet/global/exception/GlobalExceptionHandler.java
- src/main/java/com/sesac7/hellopet/global/exception/dto/response/ErrorMessage.java
ResponseStatusException 사용시 메시지를 보여주는 custom exception handler를 생성합니다.
> custom exception handler 생성[#back-15]

- src/main/java/com/sesac7/hellopet/domain/user/Service/UserService.java
- src/main/java/com/sesac7/hellopet/domain/user/controller/MeController.java
- src/main/java/com/sesac7/hellopet/domain/user/dto/response/UserDetailResponse.java
- src/main/java/com/sesac7/hellopet/domain/user/entity/UserDetail.java
사용자의 마이페이지에서 유저 상세 정보를 요청하면 유저 정보와 유저 상세 정보를 제공합니다.
> 유저 정보를 반환합니다.[#back-16]

- src/main/java/com/sesac7/hellopet/domain/user/controller/MeController.java
- src/main/java/com/sesac7/hellopet/domain/user/dto/request/UserUpdateRequest.java
- src/main/java/com/sesac7/hellopet/domain/user/dto/response/UserDetailResponse.java
- src/main/java/com/sesac7/hellopet/domain/user/dto/response/UserUpdateResponse.java
- src/main/java/com/sesac7/hellopet/domain/user/entity/User.java
- src/main/java/com/sesac7/hellopet/domain/user/entity/UserDetail.java
- src/main/java/com/sesac7/hellopet/domain/user/repository/UserDetailRepository.java
- src/main/java/com/sesac7/hellopet/domain/user/service/UserService.java
유저가 유저 수정페이지에서 수정이 허용된 항목을 수정하여 DTO로 보내면 받은 DTO를 검증하고 이상이 없다면 유저 정보에 새로 쓰고 성공한 정보를 반환합니다.
> 유저의 상세정보를 수정 할 수 있습니다.[#back-25]

- src/main/java/com/sesac7/hellopet/domain/announcement/service/AnnouncementService.java
- src/main/java/com/sesac7/hellopet/domain/application/dto/response/UserApplicationResponse.java
- src/main/java/com/sesac7/hellopet/domain/application/entity/Application.java
- src/main/java/com/sesac7/hellopet/domain/application/repository/ApplicationRepository.java
- src/main/java/com/sesac7/hellopet/domain/application/service/ApplicationService.java
- src/main/java/com/sesac7/hellopet/domain/user/controller/MeController.java
- src/main/java/com/sesac7/hellopet/domain/user/service/UserService.java
- 사용자가 마이페이지 사이드바의 ‘입양 신청 내역’ 버튼을 클릭
- 사용자가 신청한 모든 입양 신청서가 신청일(생성일) 기준으로 내림차순 정렬되어 출력
> 입양 신청 내역 조회 [#back-31]

- src/main/java/com/sesac7/hellopet/domain/board/controller/BoardController.java
- src/main/java/com/sesac7/hellopet/domain/board/dto/response/BoardResponse.java
- src/main/java/com/sesac7/hellopet/domain/board/service/BoardService.java
- 엔드포인트(/boards/{boardId}) 에서 게시글 삭제가 가능합니다.
- 해당 게시글의 작성자와 동일한지 확인 후, 동일 작성자일 경우 게시글 삭제가 가능합니다.
- 삭제하기 버튼 클릭 시, 게시글이  삭제됩니다.
> feat: 자유게시판 게시글 삭제 메서드 [#back-23]

- src/main/java/com/sesac7/hellopet/domain/application/controller/ApplicationController.java
- src/main/java/com/sesac7/hellopet/domain/application/dto/response/detail/AgreementInfoResponse.java
- src/main/java/com/sesac7/hellopet/domain/application/dto/response/detail/ApplicationDetailResponse.java
- src/main/java/com/sesac7/hellopet/domain/application/dto/response/detail/CareInfoResponse.java
- src/main/java/com/sesac7/hellopet/domain/application/dto/response/detail/FamilyInfoResponse.java
- src/main/java/com/sesac7/hellopet/domain/application/dto/response/detail/FinancialInfoResponse.java
- src/main/java/com/sesac7/hellopet/domain/application/dto/response/detail/FuturePlanInfoResponse.java
- src/main/java/com/sesac7/hellopet/domain/application/dto/response/detail/HousingInfoResponse.java
- src/main/java/com/sesac7/hellopet/domain/application/dto/response/detail/PetExperienceInfoResponse.java
- src/main/java/com/sesac7/hellopet/domain/application/entity/Application.java
- src/main/java/com/sesac7/hellopet/domain/application/service/ApplicationService.java
사용자가 마이페이지 입양 신청 내역에서 본인이 신청한 입양 신청서를 삭제할 수 있음
> 입양 신청서 취소(삭제) 기능 구현 [#back-43]

- src/main/java/com/sesac7/hellopet/domain/board/dto/request/BoardSearchRequest.java
- src/main/java/com/sesac7/hellopet/domain/board/dto/request/SearchType.java
- src/main/java/com/sesac7/hellopet/domain/board/repository/BoardRepository.java
- src/main/java/com/sesac7/hellopet/domain/board/service/BoardService.java
- src/main/java/com/sesac7/hellopet/domain/user/controller/MeController.java
- 로그인 한 사용자가 마이페이지에서 내가 쓴 게시글 버튼을 클릭 시, 내가 쓴 게시글을 조회할 수 있습니다. (/me/boards)
- 자유게시판에 작성한 내가 쓴 게시글 리스트 목록이 조회됩니다.
> 내가 쓴 게시글 조회 [#back-29]

- src/main/java/com/sesac7/hellopet/domain/application/dto/request/ApplicationCreateRequest.java
- src/main/java/com/sesac7/hellopet/domain/application/dto/response/ApplicationResponse.java
- src/main/java/com/sesac7/hellopet/domain/application/entity/Application.java
- src/main/java/com/sesac7/hellopet/domain/application/entity/info/agreement/AgreementInfo.java
- src/main/java/com/sesac7/hellopet/domain/application/entity/info/care/CareInfo.java
- src/main/java/com/sesac7/hellopet/domain/application/entity/info/experience/PetExperienceInfo.java
- src/main/java/com/sesac7/hellopet/domain/application/entity/info/family/FamilyInfo.java
- src/main/java/com/sesac7/hellopet/domain/application/entity/info/financial/FinancialInfo.java
- src/main/java/com/sesac7/hellopet/domain/application/entity/info/housing/HousingInfo.java
- src/main/java/com/sesac7/hellopet/domain/application/entity/info/plan/FuturePlanInfo.java
- src/main/java/com/sesac7/hellopet/domain/application/service/ApplicationService.java
- 애플리케이션 생성 과정에서 사용되는 엔티티와 DTO에 정적 팩토리 메서드를 추가하여 객체 생성 책임을 위임함
- 서비스 코드에서 직접 빌더 호출을 제거하고, 정적 팩토리 메서드 활용으로 가독성과 유지보수성을 높임
> 입양 신청서 생성 코드 리팩토링 [#back-41]

- src/main/java/com/sesac7/hellopet/domain/comment/dto/request/CommentSearchRequest.java
- src/main/java/com/sesac7/hellopet/domain/comment/repository/CommentRepository.java
- src/main/java/com/sesac7/hellopet/domain/comment/service/CommentService.java
- src/main/java/com/sesac7/hellopet/domain/user/controller/MeController.java
- 로그인 한 사용자가 마이페이지에서 내가 쓴 댓글 버튼을 클릭 시, 내가 쓴 댓글만 조회할 수 있습니다. (/me/comments)
- 자유게시판에 작성한 내가 쓴 댓글 리스트 목록이 조회됩니다.
> 내가 쓴 댓글 조회 [#back-30]

- src/main/java/com/sesac7/hellopet/domain/user/controller/UserController.java
- src/main/java/com/sesac7/hellopet/domain/user/dto/request/UserAscDesc.java
- src/main/java/com/sesac7/hellopet/domain/user/dto/request/UserSearchRequest.java
- src/main/java/com/sesac7/hellopet/domain/user/dto/request/UserSearchType.java
- src/main/java/com/sesac7/hellopet/domain/user/dto/request/UserSortType.java
- src/main/java/com/sesac7/hellopet/domain/user/dto/response/AdminUserListResponse.java
- src/main/java/com/sesac7/hellopet/domain/user/dto/response/AdminUserResponse.java
- src/main/java/com/sesac7/hellopet/domain/user/dto/response/UserPageResponse.java
- src/main/java/com/sesac7/hellopet/domain/user/repository/UserRepository.java
- src/main/java/com/sesac7/hellopet/domain/user/service/UserService.java
- 관리자는 마이페이지의 컴포넌트에서 유저 리스트를 볼 수 있습니다.
- 관리자는 유저리스트에서 이메일이나 닉네임 검색을 통해 유저를 검색 할 수 있습니다.
> 관리자가 유저리스트를 볼 수 있습니다.[#back-38]

- src/main/java/com/sesac7/hellopet/domain/user/controller/AdminController.java
- src/main/java/com/sesac7/hellopet/domain/user/service/UserService.java
관리자는 유저를 선택하고 그 유저가 비활성화 되어있지 않으면 유저를 비활성화 시키고 아니라면 에러메시지를 반환합니다.
> 관리자는 유저를 비활성화 할 수 있습니다.[#back-47]

- src/main/java/com/sesac7/hellopet/domain/announcement/controller/AnnouncementController.java
- src/main/java/com/sesac7/hellopet/domain/announcement/repository/AnnouncementRepository.java
- src/main/java/com/sesac7/hellopet/domain/announcement/service/AnnouncementService.java
> 입양 공고 조회 시 IN_PROGRESS 상태 조건 추가 [#back-52]

- src/main/java/com/sesac7/hellopet/domain/application/repository/ApplicationRepository.java
- src/main/java/com/sesac7/hellopet/domain/application/service/ApplicationService.java
- src/main/java/com/sesac7/hellopet/domain/application/validation/AlreadyProcessedApplicationException.java
- src/main/java/com/sesac7/hellopet/domain/application/validation/DuplicateApplicationException.java
- src/main/java/com/sesac7/hellopet/domain/application/validation/ExceptionResponse.java
- src/main/java/com/sesac7/hellopet/global/config/SecurityConfig.java
- src/main/java/com/sesac7/hellopet/global/exception/GlobalExceptionHandler.java
- 한 번 승인된 신청서는 다시 승인할 수 없어야 함
- 중복 승인 시도하면 커스텀 예외를 발생시켜 의미 있는 정보 전달
> 입양 신청서 중복 승인 예외 처리 [#back-58]

- src/main/java/com/sesac7/hellopet/domain/application/repository/ApplicationRepository.java
- src/main/java/com/sesac7/hellopet/domain/application/service/ApplicationService.java
- src/main/java/com/sesac7/hellopet/domain/application/validation/DuplicateApplicationException.java
- src/main/java/com/sesac7/hellopet/domain/application/validation/ExceptionResponse.java
- src/main/java/com/sesac7/hellopet/global/config/SecurityConfig.java
- src/main/java/com/sesac7/hellopet/global/exception/GlobalExceptionHandler.java
- 사용자만 입양 신청서를 생성할 수 있음
- 보호소 관리자나 비인증 사용자는 입양 신청서를 생성할 수 없음
> 입양 신청서 생성 권한 사용자로 제한 [#back-57]

- src/main/java/com/sesac7/hellopet/domain/auth/authService/AuthService.java
- src/main/java/com/sesac7/hellopet/domain/auth/authService/RefreshFinder.java
- src/main/java/com/sesac7/hellopet/domain/auth/authService/RefreshFinderImpl.java
- src/main/java/com/sesac7/hellopet/domain/auth/repository/RefreshTokenRepository.java
- src/main/java/com/sesac7/hellopet/global/exception/custom/UnauthorizedException.java
리프래시 토큰이 만료되지 않았음에도 refresh repo에 없는 유저가 요청을 보내면 강제적으로 로그아웃되게 합니다.
> 비정상적인 로그인 회원 강제 로그아웃[#back-62]

- src/main/java/com/sesac7/hellopet/common/utils/security/AnnouncementSecurity.java
- src/main/java/com/sesac7/hellopet/common/utils/security/ApplicationSecurity.java
- src/main/java/com/sesac7/hellopet/common/utils/security/BoardSecurity.java
- src/main/java/com/sesac7/hellopet/domain/board/controller/BoardController.java
- src/main/java/com/sesac7/hellopet/domain/board/service/BoardService.java
- src/main/java/com/sesac7/hellopet/global/annotation/IsAnnouncementOwner.java
- src/main/java/com/sesac7/hellopet/global/annotation/IsApplicationOwner.java
- src/main/java/com/sesac7/hellopet/global/annotation/IsBoardOwner.java
- src/main/java/com/sesac7/hellopet/global/config/SecurityConfig.java
- src/main/java/com/sesac7/hellopet/global/filter/JwtFilter.java
커스텀 어노테이션을 만들어 간단하게 작성자인지 확인 할 수 있는 메서드를 쓸 수 있게 합니다.
> 커스텀 어노테이션과 Spel을 활용한 유저확인[#back-55]

- src/main/java/com/sesac7/hellopet/domain/board/controller/BoardController.java
- src/main/java/com/sesac7/hellopet/domain/board/service/BoardService.java
- src/main/java/com/sesac7/hellopet/domain/comment/service/CommentService.java
> feat: 정렬기능 추가 구현

- src/main/java/com/sesac7/hellopet/domain/auth/authService/AuthService.java
- src/main/java/com/sesac7/hellopet/domain/auth/repository/RefreshTokenRepository.java
기존 refresh토큰 존재를 확인 후 없으면 저장하고 있으면 넘어가던 것을 로그인 시 무조건 삭제 후 저장하도록 변경
> refresh 토큰 로테이션[#back-67]

- src/main/java/com/sesac7/hellopet/domain/board/dto/response/BoardResponse.java
> fix : BoardResponse email 필드 추가

- src/main/java/com/sesac7/hellopet/domain/comment/dto/response/CommentResponse.java
> fix: 댓글응답 email 필드 추가

- src/main/java/com/sesac7/hellopet/domain/auth/authService/AuthService.java
- src/main/java/com/sesac7/hellopet/domain/auth/authService/RefreshFinder.java
- src/main/java/com/sesac7/hellopet/domain/auth/authService/RefreshFinderImpl.java
- src/main/java/com/sesac7/hellopet/domain/auth/authService/RefreshMemoryFinderImpl.java
- src/main/java/com/sesac7/hellopet/domain/auth/entity/RefreshToken.java
- src/main/java/com/sesac7/hellopet/domain/user/service/UserFinderImpl.java
- src/main/java/com/sesac7/hellopet/domain/user/service/UserFinderMemoryImpl.java
기존에 구현했던 interface의 구현체를 개선된 구현채로 교체합니다.
> 의존성 역전 패턴 추가[#back-70]

- src/main/java/com/sesac7/hellopet/domain/comment/controller/CommentController.java
- src/main/java/com/sesac7/hellopet/domain/comment/repository/CommentRepository.java
- src/main/java/com/sesac7/hellopet/domain/comment/service/CommentService.java
> fix : 댓글 조회 기능 삭제

- src/main/java/com/sesac7/hellopet/domain/application/dto/request/ApplicationPageRequest.java
- src/main/java/com/sesac7/hellopet/domain/application/repository/ApplicationRepository.java
- src/main/java/com/sesac7/hellopet/domain/application/service/ApplicationService.java
- 사용자 및 공고별 신청 내역 조회 시 페이지네이션이 정상 동작해야 함
> 페이지네이션 버그 해결 [back-72]

- src/main/java/com/sesac7/hellopet/domain/application/dto/response/ShelterApplicationResponse.java
- src/main/java/com/sesac7/hellopet/domain/application/dto/response/UserApplicationResponse.java
- 공고별 신청 내역 응답 DTO에 신청서 상태 포함
- 사용자 신청 내역 응답 DTO에서 application.getStatus().getLabel() 사용하여 한글 라벨 응답
> 신청 내역 응답 DTO 수정 [#back-73]
